const styles = {
  root: {
    fontFamily: 'DM Sans',
    minHeight: '100vh',
  },
  heading: {
    color: '#333',
    textAlign: { xs: 'center', md: 'left' },
    fontFamily: 'DM Sans',
    fontSize: { xs: '18px', md: '44px' },
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: 'normal',
    '--leading-trim': 'both',
    '--text-edge': 'cap',
  },
  subHeading: {
    color: '#333',
    fontSize: { xs: '16px', md: '26px' },
    fontStyle: 'normal',
    fontWeight: 500,
    textAlign: { xs: 'center', md: 'left' },
    paddingBottom: { xs: '8px', md: '40px' },
    lineHeight: 'normal',
  },
  inputContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: { xs: 'center', md: 'center' },
    justifyContent: { xs: 'center', md: 'center' },
    width: '100%',
    padding: { xs: '0px', md: '0 66px' },
  },
  infoBox: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: { xs: '159px', md: '300px' },
    // height: { xs: '96px', md: '85px' },
    flexShrink: 0,
    borderRadius: '8px',
    background: '#C6E2CF',
    padding: { xs: '10px', md: '20px' },
    fontSize: { xs: '11px', md: '14px' },
    gap: { xs: '5px', md: '25px' },
    flexDirection: { xs: 'column', md: 'column' },
    textAlign: 'center',
  },
  inputContainer2: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: { xs: 'center', md: 'flex-start' },
    justifyContent: { xs: 'center', md: 'flex-start' },
    width: '100%',
  },
  productContainer: {
    display: 'flex',
    height: { xs: '200px', md: '500px' },
    width: { xs: '150px', md: '400px' },
    padding: { xs: '2px', md: '20px' },
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: { xs: '6px', md: '10px' },
    alignSelf: 'stretch',
    borderRadius: { xs: '5px', md: '21px' },
    border: '1px solid #000',
  },
  addToCartButton: {
    padding: '3px 20px',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    border: '1px solid #000',
    color: '#FFF',
    textAlign: 'center',
    fontFamily: '"DM Sans", sans-serif',
    background: '#602DEE',
    fontSize: { xs: '10px', md: '15px' },
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: 'normal',
    letterSpacing: '0.8px',
    height: { xs: '22px', md: '50px' },
    width: '90%',
  },
  rangeBox: {
    display: 'flex',
    width: { xs: '70px', md: '100px' },
    height: { xs: '70px', md: '100px' },
    flexDirection: 'column',
    justifyContent: 'center',
    padding: '2px',
    alignItems: 'center',
    flexShrink: 0,
    borderRadius: '100px',
  },
};

export default styles;
