// src/app/terms-and-conditions/page.tsx
'use client';

import { Container, Typography, Box, Grid2, Card, CardContent } from '@mui/material';
import { useEffect, useRef, useState } from 'react';
import EmailIcon from '@mui/icons-material/Email';
import PhoneIcon from '@mui/icons-material/Phone';
import LocationOnIcon from '@mui/icons-material/LocationOn';

const TermsAndConditions = () => {
  const [isVisible, setIsVisible] = useState(false);
  const [sectionsVisible, setSectionsVisible] = useState(false);
  const sectionRef = useRef<HTMLDivElement>(null);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          setTimeout(() => setSectionsVisible(true), 200);
        }
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, [mounted]);

  if (!mounted) {
    return (
      <Container maxWidth={false} sx={{ backgroundColor: '#fafbfc', padding: { xs: '60px 0', md: '120px 0' } }}>
        <Container maxWidth="lg">
          <Box sx={{ textAlign: 'center', py: 8 }}>
            <Typography variant="h4">Loading...</Typography>
          </Box>
        </Container>
      </Container>
    );
  }

  const sections = [
    {
      title: "1. Introduction",
      content: "These Terms & Conditions (Terms) govern your access and use of SmartSkin Africa's AI-powered skincare analysis platform (Services). By using our Services, you agree to be bound by these Terms."
    },
    {
      title: "2. Eligibility & Account Registration",
      content: "You must be at least 16 years old (or the legal age in your jurisdiction) to use our Services. By creating an account, you confirm that the information provided is accurate and that you will keep it updated. You are responsible for maintaining the confidentiality of your account credentials and for all activities conducted under your account."
    },
    {
      title: "3. Nature of Service & No Medical Advice",
      content: "Our AI-powered analysis is for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. We do not guarantee the accuracy, effectiveness, or suitability of any skincare recommendations provided. Always consult a dermatologist or medical professional before making significant skincare decisions."
    },
    {
      title: "4. User Conduct & Restrictions",
      content: "By using our platform, you agree not to:\n• Upload or submit false, misleading, or inappropriate content.\n• Attempt to reverse-engineer, modify, or exploit our AI technology.\n• Use the platform for unlawful purposes or in violation of any regulations.\n• Share, distribute, or commercialize our AI-generated reports without written authorization from us.\n\nViolation of these Terms may result in suspension or termination of your access and where applicable, legal prosecution."
    },
    {
      title: "5. Payments & Refunds (If Applicable)",
      content: "All payments are non-refundable except in cases of double charges or billing errors. We are not responsible for third-party transaction failures."
    },
    {
      title: "6. Intellectual Property Rights",
      content: "All content, algorithms, and reports generated by SmartSkin Africa are our exclusive property. Users may not copy, reproduce, or distribute AI-generated insights for commercial purposes. Any feedback or suggestions submitted to us may be used freely for service improvements without compensation."
    },
    {
      title: "7. Disclaimer of Warranties",
      content: "SmartSkin Africa provides its services on an \"as is\" and \"as available\" basis. We do not warrant that the platform will be error-free, uninterrupted, or always accurate. Users assume full responsibility for their reliance on the provided skincare insights."
    },
    {
      title: "8. Limitation of Liability",
      content: "To the fullest extent permitted by law: SmartSkin Africa shall not be liable for indirect, incidental, or consequential damages arising from service use. Our total liability shall not exceed the amount paid for the services within the past three months. Users waive any claims related to inaccuracies, product recommendations, or technical failures."
    },
    {
      title: "9. Third-Party Links & Services",
      content: "We may include links to third-party websites or services. We do not endorse or take responsibility for external content, privacy practices, or transactions."
    },
    {
      title: "10. Termination & Account Suspension",
      content: "We reserve the right to terminate or suspend access to our Services at any time, without prior notice, if:\n• Users violate these Terms.\n• Fraudulent activity is suspected.\n• Legal or security concerns arise."
    },
    {
      title: "11. Governing Law & Dispute Resolution",
      content: "These Terms shall be governed by the laws of the Republic of Ghana. Any disputes shall be resolved through arbitration in Accra, and users waive their right to a jury trial or class action."
    },
    {
      title: "12. Changes to These Terms",
      content: "We may modify these Terms at any time without recourse to users. Updates will be posted with an effective date, and continued use of the platform constitutes acceptance of the revised Terms."
    }
  ];

  const contactInfo = [
    {
      icon: EmailIcon,
      label: 'Email',
      value: 'support@smartskinafrica.com',
      href: 'mailto:support@smartskinafrica.com'
    },
    {
      icon: PhoneIcon,
      label: 'Phone',
      value: '+233 55 059 0714',
      href: 'tel:+233550590714'
    },
    {
      icon: LocationOnIcon,
      label: 'Address',
      value: 'S-03 First Floor, Friendly Heights Building\nMahama Road, Tse Addo\nAccra – Ghana',
      href: 'https://maps.google.com?q=S-03+First+Floor,+Friendly+Heights+Building,+Mahama+Road,+Tse+Addo,+Accra,+Ghana'
    }
  ];

  return (
    <Container maxWidth={false} sx={{ backgroundColor: '#fafbfc', padding: { xs: '60px 0', md: '120px 0' } }}>
      <Container maxWidth="lg">
        <Box ref={sectionRef}>
          {/* Header */}
          <Box sx={{ textAlign: 'center', mb: { xs: 6, md: 8 } }}>
            <Box
              sx={{
                width: '60px',
                height: '2px',
                background: 'linear-gradient(135deg, #E5BC76 0%, #C6A461 100%)',
                margin: '0 auto 40px',
                opacity: isVisible ? 1 : 0,
                transform: isVisible ? 'scaleX(1)' : 'scaleX(0)',
                transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                transformOrigin: 'center',
              }}
            />
            
            <Typography 
              variant="h4" 
              component="h1"
              sx={{
                fontSize: { xs: '28px', md: '36px' },
                fontWeight: 700,
                lineHeight: { xs: '36px', md: '44px' },
                color: '#1a1a1a',
                letterSpacing: '-0.02em',
                mb: 2,
                opacity: isVisible ? 1 : 0,
                transform: isVisible ? 'translateY(0)' : 'translateY(30px)',
                transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                transitionDelay: '0.1s',
              }}
            >
              SMARTSKIN AFRICA -{' '}
              <Box
                component="span"
                sx={{
                  background: 'linear-gradient(135deg, #E5BC76 0%, #C6A461 100%)',
                  backgroundClip: 'text',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                }}
              >
                TERMS & CONDITIONS
              </Box>
            </Typography>

            <Typography 
              variant="subtitle1" 
              sx={{
                fontSize: { xs: '14px', md: '16px' },
                color: '#666',
                fontWeight: 500,
                opacity: isVisible ? 1 : 0,
                transform: isVisible ? 'translateY(0)' : 'translateY(20px)',
                transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                transitionDelay: '0.2s',
              }}
            >
              Effective Date: 1st FEBRUARY 2025
            </Typography>
          </Box>

          {/* Content Sections */}
          <Box sx={{ maxWidth: '800px', margin: '0 auto' }}>
            {sections.map((section, index) => (
              <Box
                key={index}
                sx={{
                  mb: { xs: 4, md: 6 },
                  padding: { xs: '24px', md: '32px' },
                  backgroundColor: '#ffffff',
                  borderRadius: '16px',
                  boxShadow: '0 4px 24px rgba(0, 0, 0, 0.06)',
                  border: '1px solid rgba(0, 0, 0, 0.06)',
                  opacity: sectionsVisible ? 1 : 0,
                  transform: sectionsVisible ? 'translateY(0)' : 'translateY(30px)',
                  transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                  transitionDelay: `${0.1 * index}s`,
                  '&:hover': {
                    transform: sectionsVisible ? 'translateY(-4px)' : 'translateY(30px)',
                    boxShadow: '0 8px 40px rgba(0, 0, 0, 0.1)',
                  },
                }}
              >
                <Typography 
                  variant="h6" 
                  sx={{
                    fontSize: { xs: '18px', md: '20px' },
                    fontWeight: 600,
                    color: '#1a1a1a',
                    mb: 2,
                  }}
                >
                  {section.title}
                </Typography>
                <Typography
                  sx={{
                    fontSize: { xs: '14px', md: '16px' },
                    lineHeight: 1.7,
                    color: '#666',
                    whiteSpace: 'pre-line',
                  }}
                >
                  {section.content}
                </Typography>
              </Box>
            ))}

            {/* Enhanced Contact Information Section */}
            <Box
              sx={{
                mt: { xs: 6, md: 8 },
                opacity: sectionsVisible ? 1 : 0,
                transform: sectionsVisible ? 'translateY(0)' : 'translateY(30px)',
                transition: 'all 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)',
                transitionDelay: '1.2s',
              }}
            >
              <Card
                sx={{
                  borderRadius: '20px',
                  border: '1px solid rgba(0, 121, 107, 0.15)',
                  background: 'linear-gradient(135deg, rgba(0, 121, 107, 0.08) 0%, rgba(229, 188, 118, 0.05) 100%)',
                  overflow: 'hidden',
                  boxShadow: '0 8px 32px rgba(0, 0, 0, 0.08)',
                }}
              >
                <CardContent sx={{ p: { xs: 4, md: 6 } }}>
                  <Typography 
                    variant="h5" 
                    sx={{
                      fontSize: { xs: '20px', md: '24px' },
                      fontWeight: 600,
                      color: '#1a1a1a',
                      mb: 2,
                      textAlign: 'center',
                    }}
                  >
                    Contact Information
                  </Typography>
                  
                  <Typography
                    sx={{
                      fontSize: { xs: '14px', md: '16px' },
                      color: '#666',
                      textAlign: 'center',
                      mb: 4,
                      lineHeight: 1.6,
                    }}
                  >
                    If you have any questions, concerns or requests regarding our Terms and Conditions, 
                    please don't hesitate to contact us using any of the methods below.
                  </Typography>

                  <Grid2 container spacing={3}>
                    {contactInfo.map((contact, index) => (
                      <Grid2 key={index} size={{ xs: 12, md: 4 }}>
                        <Box
                          component="a"
                          href={contact.href}
                          target={contact.label === 'Address' ? '_blank' : undefined}
                          rel={contact.label === 'Address' ? 'noopener noreferrer' : undefined}
                          sx={{
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'center',
                            textAlign: 'center',
                            padding: '24px 16px',
                            backgroundColor: '#ffffff',
                            borderRadius: '16px',
                            textDecoration: 'none',
                            color: 'inherit',
                            transition: 'all 0.3s ease',
                            border: '1px solid rgba(0, 0, 0, 0.06)',
                            '&:hover': {
                              transform: 'translateY(-4px)',
                              boxShadow: '0 8px 30px rgba(0, 121, 107, 0.15)',
                              borderColor: 'rgba(0, 121, 107, 0.2)',
                            },
                          }}
                        >
                          <Box
                            sx={{
                              width: 48,
                              height: 48,
                              borderRadius: '50%',
                              backgroundColor: 'rgba(0, 121, 107, 0.1)',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                              mb: 2,
                            }}
                          >
                            <contact.icon sx={{ color: '#00796B', fontSize: 24 }} />
                          </Box>
                          
                          <Typography
                            variant="h6"
                            sx={{
                              fontSize: '16px',
                              fontWeight: 600,
                              color: '#00796B',
                              mb: 1,
                            }}
                          >
                            {contact.label}
                          </Typography>
                          
                          <Typography
                            sx={{
                              fontSize: '14px',
                              color: '#666',
                              lineHeight: 1.5,
                              whiteSpace: 'pre-line',
                            }}
                          >
                            {contact.value}
                          </Typography>
                        </Box>
                      </Grid2>
                    ))}
                  </Grid2>

                  <Box
                    sx={{
                      mt: 4,
                      pt: 3,
                      borderTop: '1px solid rgba(0, 0, 0, 0.1)',
                      textAlign: 'center',
                    }}
                  >
                    <Typography
                      sx={{
                        fontSize: '12px',
                        color: '#999',
                        fontStyle: 'italic',
                      }}
                    >
                      We typically respond to all inquiries within 24-48 hours during business days.
                    </Typography>
                  </Box>
                </CardContent>
              </Card>
            </Box>
          </Box>
        </Box>
      </Container>
    </Container>
  );
};

export default TermsAndConditions;