import { Container, Typography, Box } from '@mui/material';

const TermsAndConditions = () => {
  return (
    <Container maxWidth={false} sx={{ backgroundColor: '#f6f9f9', padding: { xs: 0, md: 5 } }}>
      <Container maxWidth="lg">
        <Typography variant="h4" align="center" gutterBottom sx={{ fontWeight: 'bold', mb: 4 }}>
          SMARTSKIN AFRICA - TERMS & CONDITIONS
        </Typography>
        <Typography variant="subtitle1" gutterBottom>
          Effective Date: 1st FEBRUARY 2025
        </Typography>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">1. Introduction</Typography>
          <Typography>
            These Terms & Conditions (Terms) govern your access and use of SmartSkin Africa’s AI-powered skincare
            analysis platform (Services). By using our Services, you agree to be bound by these Terms.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">2. Eligibility & Account Registration</Typography>
          <Typography>
            You must be at least 16 years old (or the legal age in your jurisdiction) to use our Services. By creating
            an account, you confirm that the information provided is accurate and that you will keep it updated. You are
            responsible for maintaining the confidentiality of your account credentials and for all activities conducted
            under your account.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">3. Nature of Service & No Medical Advice</Typography>
          <Typography>
            Our AI-powered analysis is for informational purposes only and is not a substitute for professional medical
            advice, diagnosis, or treatment. We do not guarantee the accuracy, effectiveness, or suitability of any
            skincare recommendations provided. Always consult a dermatologist or medical professional before making
            significant skincare decisions.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">4. User Conduct & Restrictions</Typography>
          <Typography>
            By using our platform, you agree not to:
            <ul>
              <li>Upload or submit false, misleading, or inappropriate content.</li>
              <li>Attempt to reverse-engineer, modify, or exploit our AI technology.</li>
              <li>Use the platform for unlawful purposes or in violation of any regulations.</li>
              <li>
                Share, distribute, or commercialize our AI-generated reports without written authorization from us.
              </li>
            </ul>
            Violation of these Terms may result in suspension or termination of your access and where applicable, legal
            prosecution.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">5. Payments & Refunds (If Applicable)</Typography>
          <Typography>
            All payments are non-refundable except in cases of double charges or billing errors. We are not responsible
            for third-party transaction failures.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">6. Intellectual Property Rights</Typography>
          <Typography>
            All content, algorithms, and reports generated by SmartSkin Africa are our exclusive property. Users may not
            copy, reproduce, or distribute AI-generated insights for commercial purposes. Any feedback or suggestions
            submitted to us may be used freely for service improvements without compensation.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">7. Disclaimer of Warranties</Typography>
          <Typography>
            SmartSkin Africa provides its services on an "as is" and "as available" basis. We do not warrant that the
            platform will be error-free, uninterrupted, or always accurate. Users assume full responsibility for their
            reliance on the provided skincare insights.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">8. Limitation of Liability</Typography>
          <Typography>
            To the fullest extent permitted by law: SmartSkin Africa shall not be liable for indirect, incidental, or
            consequential damages arising from service use. Our total liability shall not exceed the amount paid for the
            services within the past three months. Users waive any claims related to inaccuracies, product
            recommendations, or technical failures.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">9. Third-Party Links & Services</Typography>
          <Typography>
            We may include links to third-party websites or services. We do not endorse or take responsibility for
            external content, privacy practices, or transactions.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">10. Termination & Account Suspension</Typography>
          <Typography>
            We reserve the right to terminate or suspend access to our Services at any time, without prior notice, if:
            <ul>
              <li>Users violate these Terms.</li>
              <li>Fraudulent activity is suspected.</li>
              <li>Legal or security concerns arise.</li>
            </ul>
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">11. Governing Law & Dispute Resolution</Typography>
          <Typography>
            These Terms shall be governed by the laws of the Republic of Ghana. Any disputes shall be resolved through
            arbitration in Accra, and users waive their right to a jury trial or class action.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">12. Changes to These Terms</Typography>
          <Typography>
            We may modify these Terms at any time without recourse to users. Updates will be posted with an effective
            date, and continued use of the platform constitutes acceptance of the revised Terms.
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="h6">Contact Information</Typography>
          <Typography>
            If you have any questions, concerns or requests regarding our Terms and Conditions, you may contact us using
            the details below:
            <br />
            <strong>Email:</strong> support@smartskinafrica.com
            <br />
            <strong>Phone:</strong> +233550590714
            <br />
            <strong>Address:</strong> S-03 First Floor, Friendly Heights Building, Mahama Road, Tse Addo, Accra – Ghana
          </Typography>
        </Box>
      </Container>
    </Container>
  );
};

export default TermsAndConditions;
